# Generated by Django 4.2.14 on 2024-08-04 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.FileField(null=True, upload_to='image')),
                ('answer', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('session', models.UUIDField(default=uuid.uuid4)),
                ('point', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
